services:
  - type: web
    name: survivorflow-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_URL
        sync: false  # Value will be added manually via Render Dashboard
